name: CI/CD for C# App with Build-Test-Deploy Stages

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4  # Оновлено до v4
      - name: .NET Installation
        uses: actions/setup-dotnet@v4  # Оновлено до v4
        with:
          dotnet-version: '8.0.x'
      - name: Dependencies Installation
        run: dotnet restore
      - name: Project Build
        run: dotnet build MyCSharpApp/MyCSharpApp.csproj --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4  # Оновлено до v4
      - name: .NET Installation
        uses: actions/setup-dotnet@v4  # Оновлено до v4
        with:
          dotnet-version: '8.0.x'
      - name: Dependencies Installation
        run: dotnet restore
      - name: Tests Execution
        run: dotnet test MyCSharpApp.Tests/MyCSharpApp.Tests.csproj --verbosity detailed

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4  # Оновлено до v4
      - name: .NET Installation
        uses: actions/setup-dotnet@v4  # Оновлено до v4
        with:
          dotnet-version: '8.0.x'
      - name: Dependencies Installation
        run: dotnet restore
      - name: Project Publishing
        run: dotnet publish MyCSharpApp/MyCSharpApp.csproj --configuration Release --output ./publish
      - name: Deploy Simulation
        run: echo "Deploy successfully done (simulated)"